export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';

export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
